import './styles.css';
// import './js/class';
// import './js/timer';
// import './js/interval';
// import './js/notification';
// import './js/intro_promise';
// import './js/promise';
//  import './js/promise_racetrack';
// import './js/fetch_get';
import './fetch/fetch_main';